---
id: debugging-lang
title: Debugging (Language-Specific)
author: Benjamin Qi, Aaron Chew, Aryansh Shrivastava, Owen Wang
description:
  'Identifying errors within your program and how to avoid them in the first
  place.'
---

<Resources>
	<Resource
		source="AryanshS"
		url="https://sendtoaryansh.gitbook.io/informatics-notes/debugging-correctly"
		title="Debugging Correctly"
	>
		Some parts were taken from here.
	</Resource>
	<Resource
		source="LCPP"
		url="https://www.learncpp.com/cpp-tutorial/basic-debugging-tactics/"
		title="3.4 - A Strategy for Debugging"
	>
		How to add print statements.
	</Resource>
</Resources>

## Style

<Resources>
	<Resource
		source="CF"
		title="Competitive C++ Manifesto: A Style Guide"
		url="64218"
		starred
	>
		Contains many important gems.
	</Resource>
</Resources>

## Printing Variables

### Basic Print Statements

The most basic way that you might debug is adding a print statement. This is
great and serves the purpose for the most part. For instance, we can write the
below to check the value of `x` at a point in our code.

<LanguageSection>
<CPPSection>
```cpp
#include <iostream>
using namespace std;

int x = 10;  // pretend this holds some important variable

void dbg() {
	cout << "x is " << x << endl; 
}

int main() {
	dbg();  // outputs 10
	x = 5000;
	dbg();  // now outputs 5000
}
```
</CPPSection>
<JavaSection>
```java
public class Main {
	static int x = 10;  // pretend this holds some important variable
	
	public static void main(String[] args) {
		dbg();  // outputs 10
		x = 5000;
		dbg();  // now outputs 5000
	}

	static void dbg() {
		System.out.println(x);
	}
}
```
</JavaSection>
<PySection>
```py
x = 10  # pretend this holds some important variable

def dbg():
	print(x)

dbg()  # outputs 10
x = 5000
dbg()  # now outputs 5000
```
</PySection>
</LanguageSection>

Such print statements are great on a basic level, and we can comment or define
them out of our main code when we need to compile and execute a more final
version of our code.

However, as great as print statements are, they are annoying to work with and
efficiently separate from the actual parts of our code. This is important for
example when we want an online judge (OJ) to read our output.

### Standard Error Stream

The standard error stream is a quick fix to this. Instead of
printing in the standard output stream, we can print in a whole new stream
called the standard error stream instead.

<LanguageSection>
<CPPSection>
```cpp
#include <iostream>
using namespace std;

int x = 10;

void dbg() {
	cerr << "x is " << x << endl; 
}

int main() {
	dbg();
	x = 5000;
	dbg();
}
```
</CPPSection>
<JavaSection>
```java
public class Main {
	static int x = 10;
	
	public static void main(String[] args) {
		dbg();
		x = 5000;
		dbg();
	}

	static void dbg() {
		System.err.println(x);
	}
}
```
</JavaSection>
<PySection>
```py
import sys

x = 10

def dbg():
	print(x, file=sys.stderr)

dbg()  # outputs 10
x = 5000
dbg()  # now outputs 5000
```
</PySection>
</LanguageSection>

Try running this program and you might be confused about the difference. The
content in the error stream appears right alongside that in the standard output
stream. But this is the beauty of it! And the best thing about it is, if we
submit this program to an OJ, it won't notice the output in the error stream
at all!

<Warning>

Printing too much content (even to the error stream) can cause TLE when
submitting to an OJ.

</Warning>

<LanguageSection>
<CPPSection>

### Debug Template

As C++ does not contain built-in print functions for many of its built-in
data structures, it would be good to have some prewritten code to print them.
[This](https://gist.github.com/SansPapyrus683/61b65d4d7ec223b48ebf5c3bb382ba8d)
template is rather easy to use. It includes support for basically all of the
needed data structures in competitive programming. Here's how you would use it:
```cpp
#include <iostream>
#include <vector>

#include "debugging.h"

using namespace std;

int main() {
	vector<int> arr{1, 2, 3, 4};
	cout << arr << endl;  // just feed it into cout like any other variable
}
```

<Warning>
You are not allowed to use pre-written code for USACO contests, so this template
should only be used for other online contests.
</Warning>

### Getting the Line Number

Sometimes, you'd like to know around which line your code is erroring at.
To print the line number, you can use the `__LINE__` macro like so:
```cpp
#include <iostream>
using namespace std;

int main() {
	cout << __LINE__ << endl;  // outputs 5, the current line number
}
```

### Checking for OOB

C++ usually silently fails (or segfaults) when you access or write to a
vector at an index that's out-of-bounds (writing to an invalid index is called
[buffer overflow](https://en.wikipedia.org/wiki/Buffer_overflow)).

For example, the following code doesn't behave as expected:

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	vector<int> invalid_vec{1};
	vector<int> valid_vec{1234};
	cout << valid_vec[0] << "\n";  // outputs 1234
	for (int i = 0; i < 10; i++) {
		invalid_vec[i] = i;
	}
	cout << valid_vec[0] << "\n";  // errors
}
```

To prevent this, you can use
[vector::at](https://www.cplusplus.com/reference/vector/vector/at) instead of
[vector::operator[]](https://www.cplusplus.com/reference/vector/vector/operator[]).

If we use this in our following code segment like so:
```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	vector<int> invalid_vec{1};
	vector<int> valid_vec{1234};
	cout << valid_vec.at(0) << "\n";  // outputs 1234
	for (int i = 0; i < 10; i++) {
		invalid_vec.at(i) = i;
	}
	cout << valid_vec.at(0) << "\n";  // errors
}
```

C++ will now check the bounds when we access the vectors and will
produce the following output:
```
1234
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
1 zsh: abort      ./$1 $@[2,-1]
```

If you want to find out the exact line at which this error occurs, you can use
a debugger such as `gdb` or `lldb`.

### Unspecified Evaluation Order

Consider the following code stored in `bad.cpp`:

```cpp
#include <bits/stdc++.h>
using namespace std;

vector<int> res{-1};

int add_element() {
	res.push_back(-1);
	return res.size() - 1;
}

int main() {
	for (int i = 0; i < 5; ++i) {
		res[i] = add_element();
		cout << i << " " << res[i] << "\n";
	}
}
```

Compiling and running the above code with C++17 as so:

```
g++ -std=c++17 bad.cpp -o bad && ./bad
```

gives the intended output:

```
0 1
1 2
2 3
3 4
4 5
```

But compiling and running with C++14 like this:

```
g++ -std=c++14 bad.cpp -o bad && ./bad
```

gives:

```
0 -1
1 -1
2 3
3 -1
4 5
```

However, the code works correctly if you save the result of `add_element()` to an
intermediate variable.

```cpp
int main() {
	for (int i = 0; i < 10; ++i) {
		int tmp = add_element();
		res[i] = tmp;
		cout << i << " " << res[i] << "\n";
	}
}
```

<!-- See [this](https://codeforces.com/blog/entry/83241) CF blog post and  -->

The problem is that `res[i] = add_element();` only works if `add_element()` is
evaluated before `res[i]` is. If `res[i]` is evaluated first, and _then_
`add_element()` results in the memory for `res` being reallocated, then `res[i]`
is invalidated. The order in which `res[i]` and `add_element()` are evaluated is
unspecified (at least before C++17).

See
[this](https://stackoverflow.com/questions/38501587/what-are-the-evaluation-order-guarantees-introduced-by-c17#:~:text=In%20C%2B%2B17%2C%20it,of%20the%20object%20is%20evaluated)
StackOverflow post for some discussion about why this is the case
([here](https://stackoverflow.com/questions/18040037)'s a similar issue).

You also may come across this issue when trying to create a
[trie](https://codeforces.com/blog/entry/83241#comment-705458).

</CPPSection>
<JavaSection> </JavaSection>
<PySection> </PySection>
</LanguageSection>

## Stress Testing

If your code is getting WA, one option is to run your buggy code against another
that you're relatively confident is correct on randomly generated data until you
find a difference. See the video for details.

<Resources>
	<Resource
		source="Errichto"
		title="Video - How to test your solution"
		url="https://www.youtube.com/watch?v=JXTVOyQpSGM"
		starred
	>
		Using a script for stress testing.
	</Resource>
	<Resource
		source="Errichto"
		title="Asking for help FAQ"
		url="https://codeforces.com/blog/entry/64993"
		starred
	>
		Contains some parts from the above videos.
	</Resource>
	<Resource
		source="Benq"
		url="https://github.com/bqi343/USACO/blob/master/Implementations/content/contest/stress.sh"
		title="Stress Testing"
	>
		The script from the above video.
	</Resource>
</Resources>

<LanguageSection>
<CPPSection>
Here is the script that was mentioned in the video:

```
# A and B are executables you want to compare, gen takes int
# as command line arg. Usage: 'sh stress.sh'
for ((i = 1; ; ++i)); do  # if they are same then will loop forever
    echo $i
    ./gen $i > int
    ./A < int > out1
    ./B < int > out2
    diff -w out1 out2 || break
    # diff -w <(./A < int) <(./B < int) || break
done
```

We can modify this to work for other situations. For example, if you have
input and output files (ex. `1.in`, `1.out`, `2.in`, `2.out`, ..., `10.out` for
old USACO problems) then you can use the following:

```
# A is the executable you want to test
for ((i = 1; i <= 10; ++i)); do
    echo $i
    ./A < $i.in > out
    diff -w out $i.out || break
done
echo "ALL TESTS PASSED"
```

The following will break on the first input file such that the produced output
file is empty.

```
for((i = 1; ; ++i)); do
	echo $i
	./gen $i > int
	./A < int > out
	if ! [[ -s "out" ]] ; then
		echo "no output"
		break
	fi ;
done
```

<Warning>
This won't work if you're using Windows. Instead, you can use what
[tourist](https://www.youtube.com/watch?v=JU3HY5GLVnY&t=58m58s) does:

```
:: save this in test.bat

@echo off
gen > in
your_sol out
correct_sol correct_out
fc out correct_out
if errorlevel 1 exit
test
```
</Warning>
</CPPSection>
<JavaSection>

Here is an script to test a Java program with input and output files. You will
need to put the `.java`, this script, and the input and output files (`1.in`,
`1.out`, etc.) in the same directory:

<Spoiler title="Java testing script">

```
#!/bin/bash
RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m"

wrong=0

fileName=$(ls | grep java)

IFS="."
read -ra fileArr <<< $fileName

className=${fileArr[0]}

loop=true
testCase=1

while $loop; do
	# Does this test case exist?
	if [[ ! -e "$testCase.in" || ! -e "$testCase.out" ]]; then
		# If not, then stop.
		break;
	fi

	# If so, then test.
	echo "Testing: $testCase"
	cp $testCase.in $className.in
	java $className.java < $className.in > $className.out

	diffOut=$(diff -w $testCase.out $className.out 2>&1)

	if [[ $diffOut == "" ]]; then
		echo -e "$GREEN** PASSED **$NC\n"
	else
		echo -e "$RED** FAILED **$NC"
		echo -e "$diffOut\n"
		wrong=$((wrong += 1))
	fi

	testCase=$((testCase += 1))
done

# Check if any wrong.
if [[ wrong -gt 0 ]]; then
	if [[ $wrong == 1 ]]; then
		echo -e "$RED*** $wrong/$testCase TEST CASE FAILED ***$NC"
	else
		echo -e "$RED*** $wrong/$((testCase - 1)) TEST CASES FAILED ***$NC"
	fi
else
	echo -e "$GREEN*** ALL TEST CASES PASSED ***$NC"
fi
```

</Spoiler>
</JavaSection>
</LanguageSection>

If you want to learn how to write these scripts yourself, you can check
[here](/general/cpp-command#linux).

<LanguageSection>
<CPPSection>

## Assertions & Warnings

<Resources>
	<Resource
		title="Asserts"
		source="LCpp"
		url="https://www.learncpp.com/cpp-tutorial/7-12a-assert-and-static_assert/"
		starred
	>
		Includes `static_assert` and `#define NDEBUG`.
	</Resource>
	<Resource
		title="5 - Diagnostics"
		source="GCC"
		url="https://gcc.gnu.org/onlinedocs/cpp/Diagnostics.html"
		starred
	>
		Talks about `#warning` and `#error`.
	</Resource>
</Resources>

## GCC Compilation Options

<Resources>
	<Resource
		source="CF"
		title="andreyv - Catching Mistakes with GCC"
		url="https://codeforces.com/blog/entry/15547"
		starred
	>
		Includes all the options mentioned below.
	</Resource>
</Resources>

You can also check what options
[Errichto](https://codeforces.com/blog/entry/64993) and
[ecnerwala](https://gist.github.com/ecnerwala/a3c6332ac626bc448165) use.

### Warning Options

In this section we'll go over some extra compilations you can add to your
`g++` compiling to aid in debugging. You can find the official documentation
for said options [here](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html).

Some other options that you might find helpful
(but we won't go over) are the following:
```
-Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -Wduplicated-cond -Wlogical-op
```

#### `-Wshadow`

<Resources>
	<Resource
		source="LCPP"
		url="ttps://www.learncpp.com/cpp-tutorial/variable-shadowing-name-hiding/"
		title="6.5 - Variable Shadowing (Name Hiding)"
		starred
	/>
</Resources>

Avoid variable shadowing!

### Other Options

Let's give some examples of what each of these do.

<Warning>

These can slow down compilation time even runtime, so don't enable these when
speed is of the essence (ex. for Facebook Hacker Cup).

</Warning>

<Warning>

`-fsanitize` flags
[don't work with MinGW](https://github.com/msys2/MINGW-packages/issues/3163). If
you're using Windows but still want to use these flags, consider using
[an online compiler](https://repl.it/) (or installing Linux) instead.

</Warning>

#### [`-fsanitize=undefined`](https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html)

The following code stored in `prog.cpp` gives a segmentation fault.

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	vector<int> v;
	cout << v[-1] << endl;
}
```

`g++ prog.cpp -o prog -fsanitize=undefined && ./prog` produces:

```
/usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/bits/stl_vector.h:1043:34: runtime error: pointer index expression with base 0x000000000000 overflowed to 0xfffffffffffffffc
zsh: segmentation fault  ./prog
```

Another example with `prog.cpp` is the following:

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	int v[5];
	cout << v[5] << endl;
}
```

`g++ prog.cpp -o prog -fsanitize=undefined && ./prog` produces:

```
prog.cpp:6:13: runtime error: index 5 out of bounds for type 'int [5]'
prog.cpp:6:13: runtime error: load of address 0x7ffee0a77a94 with insufficient space for an object of type 'int'
0x7ffee0a77a94: note: pointer points here
  b0 7a a7 e0 fe 7f 00 00  25 b0 a5 0f 01 00 00 00  b0 7a a7 e0 fe 7f 00 00  c9 8c 20 72 ff 7f 00 00
              ^
```

`-fsanitize=undefined` also catches integer overflow. Let `prog.cpp` be the
following:

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	int x = 1 << 30;
	cout << x + x << endl;
}
```

`g++ prog.cpp -o prog -fsanitize=undefined && ./prog` produces:

```
prog.cpp:6:15: runtime error: signed integer overflow: 1073741824 * 2 cannot be represented in type 'int'
```

We can also use `-fsanitize=undefined` with `-fsanitize-recover`. Error recovery
for `-fsanitize=undefined` is turned on by default, but

> The `-fno-sanitize-recover=` option can be used to alter this behavior: only
> the first detected error is reported and program then exits with a non-zero
> exit code.

So if `prog.cpp` is as follows:

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	cout << (1 << 32) << endl;
	cout << (1 << 32) << endl;
	cout << (1 << 32) << endl;
}
```

then

```
g++ -fsanitize=undefined prog.cpp -o prog && ./prog
```

produces:

```
prog.cpp: In function 'int main()':
prog.cpp:5:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    5 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:6:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    6 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:7:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    7 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:5:12: runtime error: shift exponent 32 is too large for 32-bit type 'int'
0
prog.cpp:6:12: runtime error: shift exponent 32 is too large for 32-bit type 'int'
0
prog.cpp:7:12: runtime error: shift exponent 32 is too large for 32-bit type 'int'
0
```

while

```
g++ -fsanitize=undefined -fno-sanitize-recover prog.cpp -o prog && ./prog
```

produces:

```
prog.cpp: In function 'int main()':
prog.cpp:5:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    5 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:6:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    6 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:7:12: warning: left shift count >= width of type [-Wshift-count-overflow]
    7 |  cout << (1 << 32) << endl;
      |           ~^~~~
prog.cpp:5:12: runtime error: shift exponent 32 is too large for 32-bit type 'int'
zsh: abort      ./prog
```

#### `-fsanitize=address -g`

<Warning>

According to [this issue](https://github.com/msys2/MINGW-packages/issues/3163),
AddressSanitizer does not appear to be available for MinGW.

</Warning>

<Resources>
	<Resource
		source="GCC"
		title="3.10 - Options for Debugging Your Program"
		url="Debugging-Options.html"
	>
		documentation for -g, -ggdb
	</Resource>
</Resources>

The following code (stored in `prog.cpp`) gives a segmentation fault.

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	vector<int> v;
	cout << v[-1] << endl;
}
```

`g++ prog.cpp -o prog -fsanitize=address && ./prog` produces:

<Spoiler title="AddressSanitizer">
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==31035==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000106ac6326 bp 0x7ffee913aaa0 sp 0x7ffee913aa20 T0)
==31035==The signal is caused by a READ memory access.
==31035==Hint: address points to the zero page.
    #0 0x106ac6325 in main (prog:x86_64+0x100001325)
    #1 0x7fff72208cc8 in start (libdyld.dylib:x86_64+0x1acc8)

==31035==Register values:
rax = 0xfffffffffffffffc  rbx = 0x00007ffee913aa20  rcx = 0xfffffffffffffffc  rdx = 0x20000fffffffffff
rdi = 0x00007ffee913aa40  rsi = 0x1fffffffffffffff  rbp = 0x00007ffee913aaa0  rsp = 0x00007ffee913aa20
 r8 = 0x0000000000000000   r9 = 0x0000000000000000  r10 = 0x0000000000000000  r11 = 0x0000000000000000
r12 = 0x00000fffdd227544  r13 = 0x00007ffee913aa80  r14 = 0x00007ffee913aa20  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (prog:x86_64+0x100001325) in main
==31035==ABORTING
zsh: abort      ./prog
```
</Spoiler>

For more helpful information we should additionally compile with the `-g` flag,
which generates a file containing debugging information based on the line
numbering of the program. `-fsanitize=address` can then access the file at
runtime and give meaningful errors. This is great because it helps diagnose (or
"sanitize" if you will) errors such as out of bounds, exceptions, and
segmentation faults, even indicating precise line numbers. Feel free to delete
the debug file after the run of course.
<Spoiler title="AddressSanitizer with -g">

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==98773==ERROR: AddressSanitizer: SEGV on unknown address (pc 0x00010a0b5316 bp 0x7ffee5b4ba50 sp 0x7ffee5b4b9d0 T0)
==98773==The signal is caused by a READ memory access.
==98773==Hint: this fault was caused by a dereference of a high value address (see register values below).  Dissassemble the provided pc to learn which register was used.
    #0 0x10a0b5316 in main prog.cpp:6
    #1 0x7fff6f2c1cc8 in start (libdyld.dylib:x86_64+0x1acc8)

==98773==Register values:
rax = 0xfffffffffffffffc  rbx = 0x00007ffee5b4b9d0  rcx = 0xfffffffffffffffc  rdx = 0x20000fffffffffff
rdi = 0x00007ffee5b4b9f0  rsi = 0x1fffffffffffffff  rbp = 0x00007ffee5b4ba50  rsp = 0x00007ffee5b4b9d0
 r8 = 0x0000000000000000   r9 = 0x0000000000000000  r10 = 0x0000000000000000  r11 = 0x0000000000000000
r12 = 0x00007ffee5b4ba30  r13 = 0x00000fffdcb6973a  r14 = 0x00007ffee5b4b9d0  r15 = 0x0000000000000000
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV prog.cpp:6 in main
==98773==ABORTING
zsh: abort      ./prog
```

</Spoiler>

<!-- Of course, we can use `-fsanitize=address` together with `-fsanitize=undefined` and `-ggdb`:

```
-ggdb -fsanitize=address,undefined
```
 -->

Another example is with `prog.cpp` as the following:

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	int v[5];
	cout << v[5] << endl;
}
```

`g++ prog.cpp -o prog -fsanitize=address -g && ./prog` produces:

<Spoiler title="AddressSanitizer with -g">
```
=================================================================
==51610==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffee99819a4 at pc 0x00010627ece5 bp 0x7ffee9981960 sp 0x7ffee9981958
READ of size 4 at 0x7ffee99819a4 thread T0
    #0 0x10627ece4 in main prog.cpp:6
    #1 0x7fff68e63cc8 in start (libdyld.dylib:x86_64+0x1acc8)

Address 0x7ffee99819a4 is located in stack of thread T0 at offset 52 in frame
    #0 0x10627ec35 in main prog.cpp:4

  This frame has 1 object(s):
    [32, 52) 'v' (line 5) <== Memory access at offset 52 overflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism, swapcontext or vfork
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow prog.cpp:6 in main
Shadow bytes around the buggy address:
  0x1fffdd3302e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd3302f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330300: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330310: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330320: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f1 f1
=>0x1fffdd330330: f1 f1 00 00[04]f3 f3 f3 f3 f3 00 00 00 00 00 00
  0x1fffdd330340: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330350: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330360: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330370: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x1fffdd330380: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==51610==ABORTING
zsh: abort      ./prog
```
</Spoiler>

#### `-D_GLIBCXX_DEBUG`

<Resources>
	<Resource
		source="GCC"
		title="Using Debug Mode"
		url="https://gcc.gnu.org/onlinedocs/libstdc++/manual/debug_mode_using.html#debug_mode.using.mode"
	>
		documentation for -D_GLIBCXX_DEBUG
	</Resource>
</Resources>

The following `prog.cpp` gives a segmentation fault.

```cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
	vector<int> v;
	cout << v[-1] << endl;
}
```

`g++ prog.cpp -o prog -D_GLIBCXX_DEBUG && ./prog` produces:

<Spoiler title="Debug">
```
/usr/local/Cellar/gcc/9.2.0_1/include/c++/9.2.0/debug/vector:427:
In function:
    std::__debug::vector<_Tp, _Allocator>::reference
    std::__debug::vector<_Tp,
    _Allocator>::operator[](std::__debug::vector<_Tp,
    _Allocator>::size_type) [with _Tp = int; _Allocator =
    std::allocator<int>; std::__debug::vector<_Tp, _Allocator>::reference =
    int&; std::__debug::vector<_Tp, _Allocator>::size_type = long unsigned
    int]

Error: attempt to subscript container with out-of-bounds index -1, but
container only holds 0 elements.

Objects involved in the operation:
    sequence "this" @ 0x0x7ffee2503a50 {
      type = std::__debug::vector<int, std::allocator<int> >;
    }
zsh: abort      ./prog
```
</Spoiler>

</CPPSection>
<JavaSection> </JavaSection>
<PySection> </PySection>
</LanguageSection>

## Debuggers

<LanguageSection>
<CPPSection>
<Resources>
	<Resource
		source="LCPP"
		title="3.6 - Using an integrated debugger"
		url="https://www.learncpp.com/cpp-tutorial/using-an-integrated-debugger-stepping/"
	/>
	<Resource
		source="Microsoft"
		title="Debug C++ in Visual Studio Code"
		url="https://code.visualstudio.com/docs/cpp/cpp-debug"
	/>
	<Resource
		source="Jetbrains"
		title="Debugging C++ in CLion"
		url="https://www.jetbrains.com/help/clion/debugging-code.html"
	/>
</Resources>
</CPPSection>
<JavaSection>
<Resources>
	<Resource
		source="Microsoft"
		title="Debugging Java in Visual Studio Code"
		url="https://code.visualstudio.com/docs/java/java-debugging"
	/>
	<Resource
		source="Jetbrains"
		title="Debugging Java in IntelliJ"
		url="https://www.jetbrains.com/help/idea/debugging-your-first-java-application.html"
	/>
</Resources>
</JavaSection>
<PySection>
<Resources>
	<Resource
		source="Microsoft"
		title="Debugging Python in Visual Studio Code"
		url="https://code.visualstudio.com/docs/python/debugging"
	/>
	<Resource
		source="Jetbrains"
		title="Debugging Python in PyCharm"
		url="https://www.jetbrains.com/help/pycharm/part-1-debugging-python-code.html"
	/>
</Resources>
</PySection>
</LanguageSection>

Using a debugger varies from language to language and even from IDE to different
IDE, so we will only go over the basics of a debugger.

A debugger allows you to pause a code in its execution and see the values as a
given point in the debugger.

To do this, set a "breakpoint" at a certain line of code. When the code runs to
that breakpoint, it will pause and you will be able to inspect all the different
variables at that certain instance.

There are two more useful and common operations. Once you are at the breakpoint,
you may want to see what happens after the current line is executed. This would
be the "Step Over" button that will allow you to move to the next line. Say you
are at a line with the following code: `dfs(0, -1)`, if you click "step over" the
debugger will ignore showing you what happens in this function and go to the
next line. If you click "step in," however, you will enter the function and be
able to step through that function.

In essense, a debugger is a tool to "trace code" for you. It is not much
different from just printing the values out at various points in your program.

Pros of using a debugger:

- No need to write print statements so you save time
- You can step through the code in real time

Cons of using a debugger:

- You cannot see the overall "output" of your program at each stage. For
  example, if you wanted to see every single value of `i` in the program,
  you could not using a debugger.
- Most advanced competitive programmers do not use debuggers; it is usually not
  very efficient to use one during a contest.
